services:

  postgres:
    container_name: postgres
    image: postgres
    user: root
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ${BASE_PATH}/postgres:/var/lib/postgresql/data
